"""add places.tour_matched_at

Revision ID: 06fb23255fb0
Revises: aedbf5168cc3
Create Date: 2026-08-16 16:27:42.846531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06fb23255fb0'
down_revision: Union[str, Sequence[str], None] = 'aedbf5168cc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('tour_matched_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'tour_matched_at')
    # ### end Alembic commands ###
