"""initial 7 tables minimal

Revision ID: 439ec7cb835f
Revises: 
Create Date: 2026-06-28 22:16:02.128533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision: str = '439ec7cb835f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")  # geography 타입에 필요
    op.create_table('contents',
    sa.Column('content_id', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.Enum('movie', 'drama', 'show', name='content_type'), nullable=False),
    sa.Column('title_ko', sa.String(length=200), nullable=False),
    sa.Column('poster_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('content_id', name=op.f('pk_contents'))
    )
    op.create_geospatial_table('regions',
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('area_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('centroid', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.PrimaryKeyConstraint('region_id', name=op.f('pk_regions'))
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('auth_provider', sa.Enum('google', 'kakao', name='auth_provider'), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users')),
    sa.UniqueConstraint('auth_provider', 'provider_user_id', name='uq_users_provider')
    )
    op.create_table('courses',
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_courses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', name=op.f('pk_courses'))
    )
    op.create_geospatial_table('places',
    sa.Column('place_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('geom', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('region_id', sa.BigInteger(), nullable=True),
    sa.Column('tour_content_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], name=op.f('fk_places_region_id_regions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('place_id', name=op.f('pk_places'))
    )
    op.create_geospatial_index('idx_places_geom', 'places', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('content_place_mappings',
    sa.Column('mapping_id', sa.BigInteger(), nullable=False),
    sa.Column('content_id', sa.BigInteger(), nullable=False),
    sa.Column('place_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.content_id'], name=op.f('fk_content_place_mappings_content_id_contents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['place_id'], ['places.place_id'], name=op.f('fk_content_place_mappings_place_id_places'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mapping_id', name=op.f('pk_content_place_mappings')),
    sa.UniqueConstraint('content_id', 'place_id', name='uq_cpm_content_place')
    )
    op.create_table('course_places',
    sa.Column('course_place_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('place_id', sa.BigInteger(), nullable=False),
    sa.Column('visit_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], name=op.f('fk_course_places_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['place_id'], ['places.place_id'], name=op.f('fk_course_places_place_id_places'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('course_place_id', name=op.f('pk_course_places')),
    sa.UniqueConstraint('course_id', 'visit_order', name='uq_course_places_order')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_places')
    op.drop_table('content_place_mappings')
    op.drop_geospatial_index('idx_places_geom', table_name='places', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('places')
    op.drop_table('courses')
    op.drop_table('users')
    op.drop_geospatial_table('regions')
    op.drop_table('contents')
    # 네이티브 enum 타입 정리(테이블 삭제만으론 남음)
    op.execute("DROP TYPE IF EXISTS auth_provider")
    op.execute("DROP TYPE IF EXISTS content_type")
    # ### end Alembic commands ###
