"""add api_call_logs table

Revision ID: aedbf5168cc3
Revises: c4d4fdb425b1
Create Date: 2026-08-16 16:16:10.168239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aedbf5168cc3'
down_revision: Union[str, Sequence[str], None] = 'c4d4fdb425b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_call_logs',
    sa.Column('log_id', sa.BigInteger(), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('request_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('http_status', sa.SmallInteger(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('called_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_api_call_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id', name=op.f('pk_api_call_logs'))
    )
    op.create_index('ix_api_call_logs_operation_called', 'api_call_logs', ['operation', 'called_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_api_call_logs_operation_called', table_name='api_call_logs')
    op.drop_table('api_call_logs')
    # ### end Alembic commands ###
