"""expand schema for CSV seed (regions hierarchy, content/place/mapping columns)

Revision ID: c4d4fdb425b1
Revises: 439ec7cb835f
Create Date: 2026-08-15 15:21:58.431956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4d4fdb425b1'
down_revision: Union[str, Sequence[str], None] = '439ec7cb835f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_place_mappings', sa.Column('kmdb_case_id', sa.String(length=40), nullable=True))
    op.add_column('content_place_mappings', sa.Column('scene_description', sa.Text(), nullable=True))
    op.add_column('content_place_mappings', sa.Column('characters', sa.String(length=300), nullable=True))
    op.add_column('content_place_mappings', sa.Column('episode', sa.String(length=50), nullable=True))
    op.create_unique_constraint(op.f('uq_content_place_mappings_kmdb_case_id'), 'content_place_mappings', ['kmdb_case_id'])
    op.add_column('contents', sa.Column('kmdb_code', sa.String(length=20), nullable=True))
    op.add_column('contents', sa.Column('source', sa.String(length=20), nullable=True))
    op.add_column('contents', sa.Column('source_url', sa.Text(), nullable=True))
    op.add_column('contents', sa.Column('production_year', sa.Integer(), nullable=True))
    op.add_column('contents', sa.Column('original_title', sa.String(length=300), nullable=True))
    op.add_column('contents', sa.Column('overview', sa.Text(), nullable=True))
    op.add_column('contents', sa.Column('genre_tags', postgresql.ARRAY(sa.String(length=50)), nullable=True))
    op.add_column('contents', sa.Column('tmdb_id', sa.Integer(), nullable=True))
    op.add_column('contents', sa.Column('tmdb_type', sa.String(length=10), nullable=True))
    op.add_column('contents', sa.Column('vote_average', sa.Numeric(precision=3, scale=1), nullable=True))
    op.add_column('contents', sa.Column('runtime', sa.Integer(), nullable=True))
    op.create_unique_constraint(op.f('uq_contents_kmdb_code'), 'contents', ['kmdb_code'])
    op.add_column('places', sa.Column('kmdb_place_id', sa.String(length=30), nullable=True))
    op.add_column('places', sa.Column('source', sa.String(length=20), nullable=True))
    op.add_column('places', sa.Column('address', sa.String(length=300), nullable=True))
    op.add_column('places', sa.Column('road_address', sa.String(length=300), nullable=True))
    op.create_unique_constraint(op.f('uq_places_kmdb_place_id'), 'places', ['kmdb_place_id'])
    # NOT NULL 컬럼을 기존 테이블에 추가 — 지금 regions는 0행이지만, 데이터가 있는 DB에서도
    # 안전하도록 임시 server_default로 채운 뒤 default를 떼어낸다(모델엔 default가 없으므로).
    op.add_column('regions', sa.Column('level', sa.String(length=10), nullable=False, server_default='sido'))
    op.alter_column('regions', 'level', server_default=None)
    op.add_column('regions', sa.Column('parent_region_id', sa.BigInteger(), nullable=True))
    op.add_column('regions', sa.Column('sigungu_code', sa.String(length=10), nullable=True))
    op.alter_column('regions', 'area_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.create_unique_constraint('uq_regions_parent_name', 'regions', ['parent_region_id', 'name'], postgresql_nulls_not_distinct=True)
    op.create_foreign_key(op.f('fk_regions_parent_region_id_regions'), 'regions', 'regions', ['parent_region_id'], ['region_id'], ondelete='CASCADE')
    # ### end Alembic commands ###

    # ── 수동 추가: 유저 플로우 핵심 조회 경로 인덱스 ──
    # 장르 필터('로맨스 작품만') — 배열 컬럼은 GIN이라야 @> 검색이 인덱스를 탄다.
    op.create_index('ix_contents_genre_tags', 'contents', ['genre_tags'], postgresql_using='gin')
    # 지역 → 그 지역의 촬영지(지도 마커). FK엔 인덱스가 자동 생성되지 않는다.
    op.create_index('ix_places_region_id', 'places', ['region_id'])
    # 장소 → 그 장소가 나온 작품(지역 검색 시 포스터 마커).
    # content_id 방향은 uq_cpm_content_place가 이미 커버하므로 place_id만 추가.
    op.create_index('ix_cpm_place_id', 'content_place_mappings', ['place_id'])


def downgrade() -> None:
    """Downgrade schema."""
    # 수동 추가 인덱스 되돌리기 (컬럼 DROP보다 먼저).
    op.drop_index('ix_cpm_place_id', table_name='content_place_mappings')
    op.drop_index('ix_places_region_id', table_name='places')
    op.drop_index('ix_contents_genre_tags', table_name='contents')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_regions_parent_region_id_regions'), 'regions', type_='foreignkey')
    op.drop_constraint('uq_regions_parent_name', 'regions', type_='unique')
    op.alter_column('regions', 'area_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_column('regions', 'sigungu_code')
    op.drop_column('regions', 'parent_region_id')
    op.drop_column('regions', 'level')
    op.drop_constraint(op.f('uq_places_kmdb_place_id'), 'places', type_='unique')
    op.drop_column('places', 'road_address')
    op.drop_column('places', 'address')
    op.drop_column('places', 'source')
    op.drop_column('places', 'kmdb_place_id')
    op.drop_constraint(op.f('uq_contents_kmdb_code'), 'contents', type_='unique')
    op.drop_column('contents', 'runtime')
    op.drop_column('contents', 'vote_average')
    op.drop_column('contents', 'tmdb_type')
    op.drop_column('contents', 'tmdb_id')
    op.drop_column('contents', 'genre_tags')
    op.drop_column('contents', 'overview')
    op.drop_column('contents', 'original_title')
    op.drop_column('contents', 'production_year')
    op.drop_column('contents', 'source_url')
    op.drop_column('contents', 'source')
    op.drop_column('contents', 'kmdb_code')
    op.drop_constraint(op.f('uq_content_place_mappings_kmdb_case_id'), 'content_place_mappings', type_='unique')
    op.drop_column('content_place_mappings', 'episode')
    op.drop_column('content_place_mappings', 'characters')
    op.drop_column('content_place_mappings', 'scene_description')
    op.drop_column('content_place_mappings', 'kmdb_case_id')
    # ### end Alembic commands ###
